spring:
  application:
    name: book-store

  mail:
    port: 1025
    host: localhost
    password: ""
    username: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enabled: false

application:
  jwt:
    secret-key-str: sdnkasjdnasdknsadnsakdnsakdnsakdndasdasd
    access-expiration-ms: 300000
    refresh-expiration-ms: 86400000

server:
  servlet:
    context-path: /api/v1